
export const LOAD_MOVIES_REQUEST = 'LOAD_MOVIES_REQUEST'
export const LOAD_MOVIES_SUCCESS = 'LOAD_MOVIES_SUCCESS'
export const LOAD_MOVIES_FAILURE = 'LOAD_MOVIES_FAILURE'
export const REMOVE_MOVIES_SUCCESS = 'REMOVE_MOVIES_SUCCESS'

export const FILTER_MOVIES_SUCCESS = 'FILTER_MOVIES_SUCCESS'



